database: hsqldb

server:
  port: 5000

# 直接在Spring Data JPA启动时初始化数据Schema
# JPA以及Hibernate相关的配置
spring:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      schema-locations: "classpath:db/${database}/schema.sql"
      data-locations: "classpath:db/${database}/data.sql"
      encoding: UTF-8
  web:
    resources:
      chain:
        compressed: true
        cache: true
      cache:
        period: 86400

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p})}"
  level:
    root: INFO